### ISSUE TITLE
Button not showing up

### ISSUE THREAD

**Issue by Plop** [Namo2/InPlayerEpisodePreview#23]
Hi,

I installed the latest plugin version (1.2.1.0), on Jellyfin 10.9.7, but the button is not showing up in the player. I tried on Firefox, Chrome, Brave, and tthe Android Jellyfin app, I just can't see it. I rebooted Jellyfin multiples times, even the docker container, but it doesn't work.

Could anyone help ? Thanks !

**Comment by Namo2** [comment]
Hi,

do you have some jellyfin logs for me after startup of the server?
There was a similar issue in the past.
Some permission issues caused the error.
Have a look at #10

**Comment by Plop** [comment]
Hi,

I haven't thought of looking in the logs, but you're right !

`[2024-07-06 12:41:21.278 +00:00] [INF] [62] Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Attempting to inject preview script code in "/usr/share/jellyfin/web/index.html"
[2024-07-06 12:41:21.279 +00:00] [ERR] [62] Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Encountered exception while writing to "/usr/share/jellyfin/web/index.html": "System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger`1 logger, IServerConfigurationManager configurationManager)"
[2024-07-06 12:41:21.280 +00:00] [INF] [62] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "InPlayerEpisodePreview" "1.2.1.0"`

I added the write permissions for "others" on index.html, and after restarting the server, I can see the button, thanks !

I'm wondering if there is a proper way to do that ? I'm running Jellyfin in a docker compose environment (based on https://hub.docker.com/r/linuxserver/jellyfin ), but the entire /usr/share/jellyfin directory is under root:root permissions

**Comment by Druidblack** [comment]
I use jf installed on debian. The button was not displayed either. After giving the recording rights to other users. (after restarting the server) A series selection button has appeared.

It may be worth adding this information, that most likely the lack of a button is caused by a lack of access rights and changing them can help. 

Therefore, the problem now refers to the discussion of the problem, where it is unclear what to do to make the button appear. And after this discussion, it became immediately clear what needs to be done to make the button work.

**Comment by Namo2** [comment]
Yes, I tried to describe it in the readme.
I will change it a little so that it should be clearer
